org: yoeltlvtech
app: api-example
service: api-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      -http:
        path: hello
        method: post
